# coding: utf-8

# flake8: noqa
"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from pristime_sdk.models.availability import Availability
from pristime_sdk.models.balance import Balance
from pristime_sdk.models.balances import Balances
from pristime_sdk.models.broken_constraints import BrokenConstraints
from pristime_sdk.models.constraint import Constraint
from pristime_sdk.models.continuous_work_duration_before_break import ContinuousWorkDurationBeforeBreak
from pristime_sdk.models.day_allow import DayAllow
from pristime_sdk.models.day_contract import DayContract
from pristime_sdk.models.day_costs import DayCosts
from pristime_sdk.models.day_metrics import DayMetrics
from pristime_sdk.models.day_shift_constraints import DayShiftConstraints
from pristime_sdk.models.day_time_constraints import DayTimeConstraints
from pristime_sdk.models.demand import Demand
from pristime_sdk.models.durations import Durations
from pristime_sdk.models.error_response import ErrorResponse
from pristime_sdk.models.health_check_response import HealthCheckResponse
from pristime_sdk.models.max_consecutive_workdays import MaxConsecutiveWorkdays
from pristime_sdk.models.metrics import Metrics
from pristime_sdk.models.min_break_duration import MinBreakDuration
from pristime_sdk.models.period import Period
from pristime_sdk.models.period_contract import PeriodContract
from pristime_sdk.models.period_costs import PeriodCosts
from pristime_sdk.models.period_day_constraints import PeriodDayConstraints
from pristime_sdk.models.period_metrics import PeriodMetrics
from pristime_sdk.models.period_time_constraints import PeriodTimeConstraints
from pristime_sdk.models.provided_shifts_durations import ProvidedShiftsDurations
from pristime_sdk.models.schedule_job_config import ScheduleJobConfig
from pristime_sdk.models.schedule_job_response import ScheduleJobResponse
from pristime_sdk.models.schedule_job_result import ScheduleJobResult
from pristime_sdk.models.schedule_state import ScheduleState
from pristime_sdk.models.scheduling_period import SchedulingPeriod
from pristime_sdk.models.shift import Shift
from pristime_sdk.models.shift_assignment import ShiftAssignment
from pristime_sdk.models.shift_assignment_result import ShiftAssignmentResult
from pristime_sdk.models.shift_creation_settings import ShiftCreationSettings
from pristime_sdk.models.shift_revenues import ShiftRevenues
from pristime_sdk.models.shifts import Shifts
from pristime_sdk.models.tag_count import TagCount
from pristime_sdk.models.work_duration import WorkDuration
from pristime_sdk.models.worker import Worker
from pristime_sdk.models.worker_cost import WorkerCost
from pristime_sdk.models.worker_metrics import WorkerMetrics
from pristime_sdk.models.worker_revenue import WorkerRevenue

