# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class MaxConsecutiveWorkdays(BaseModel):
    """
    Limits consecutive working days to prevent worker burnout and ensure adequate rest periods.  **Two-tier system:** - **Preferred maximum**: Soft constraint - optimizer tries to respect this limit but can exceed if necessary - **Absolute maximum**: Hard constraint - optimizer will never exceed this limit under any circumstances  Common patterns: - 5 preferred, 6 absolute: Standard Monday-Friday with weekend flexibility - 3 preferred, 5 absolute: Part-time workers with occasional full-time coverage - 6 preferred, 7 absolute: Full-time workers in 24/7 operations
    """ # noqa: E501
    preferred: Annotated[int, Field(strict=True, ge=1)] = Field(description="Target maximum consecutive workdays. The optimizer tries to stay within this limit but may exceed it to meet critical staffing needs.")
    absolute: Annotated[int, Field(strict=True, ge=1)] = Field(description="Hard maximum consecutive workdays that cannot be exceeded under any circumstances. Must be >= preferred maximum.")
    __properties: ClassVar[List[str]] = ["preferred", "absolute"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MaxConsecutiveWorkdays from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MaxConsecutiveWorkdays from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in MaxConsecutiveWorkdays) in the input: " + _key)

        _obj = cls.model_validate({
            "preferred": obj.get("preferred"),
            "absolute": obj.get("absolute")
        })
        return _obj


