# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from pristime_sdk.models.shift import Shift
from pristime_sdk.models.shift_assignment_result import ShiftAssignmentResult
from typing import Optional, Set
from typing_extensions import Self

class Shifts(BaseModel):
    """
    Complete collection of shifts after workforce scheduling optimization.  Organizes all shifts into two categories: those you provided in your request and those created automatically by the optimization algorithm to meet demands.  **Shift Categories:**  **Provided Shifts**: Existing shifts from your request - May have new worker assignments (optimized) - May remain unassigned if no suitable worker available - Tracked by your original shift IDs for easy mapping  **Created Shifts**: New shifts generated automatically - Created when demands exceed available provided shifts - Always assigned to workers (unassigned shifts aren't created) - Have new system-generated IDs  **Usage:** - Update your system with new assignments from 'provided' - Add the 'created' shifts as new schedule entries - Use shift IDs to map results back to your original data
    """ # noqa: E501
    provided: Dict[str, ShiftAssignmentResult] = Field(description="Assignment results for shifts you provided in the request, keyed by your original shift IDs. Shows which worker (if any) is now assigned to each existing shift.")
    created: List[Shift] = Field(description="New shifts automatically created by the optimization algorithm to meet staffing demands. These are additional shifts beyond what you originally provided, always with assigned workers.")
    __properties: ClassVar[List[str]] = ["provided", "created"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Shifts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in provided (dict)
        _field_dict = {}
        if self.provided:
            for _key_provided in self.provided:
                if self.provided[_key_provided]:
                    _field_dict[_key_provided] = self.provided[_key_provided].to_dict()
            _dict['provided'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in created (list)
        _items = []
        if self.created:
            for _item_created in self.created:
                if _item_created:
                    _items.append(_item_created.to_dict())
            _dict['created'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Shifts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in Shifts) in the input: " + _key)

        _obj = cls.model_validate({
            "provided": dict(
                (_k, ShiftAssignmentResult.from_dict(_v))
                for _k, _v in obj["provided"].items()
            )
            if obj.get("provided") is not None
            else None,
            "created": [Shift.from_dict(_item) for _item in obj["created"]] if obj.get("created") is not None else None
        })
        return _obj


