# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WorkerCost(BaseModel):
    """
    WorkerCost
    """ # noqa: E501
    per_hour_of_positive_flextime_balance: Optional[StrictInt] = Field(default=11, description="How much compensation is granted per flex time balance positive hour")
    per_hour_of_positive_overtime_balance: Optional[StrictInt] = Field(default=4, description="How much compensation is granted per over time balance hour")
    per_hour_of_unpreferred_period: Optional[StrictInt] = Field(default=2, description="How much cost is incurred for each hour assigned during an unpreferred period")
    __properties: ClassVar[List[str]] = ["per_hour_of_positive_flextime_balance", "per_hour_of_positive_overtime_balance", "per_hour_of_unpreferred_period"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkerCost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkerCost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in WorkerCost) in the input: " + _key)

        _obj = cls.model_validate({
            "per_hour_of_positive_flextime_balance": obj.get("per_hour_of_positive_flextime_balance") if obj.get("per_hour_of_positive_flextime_balance") is not None else 11,
            "per_hour_of_positive_overtime_balance": obj.get("per_hour_of_positive_overtime_balance") if obj.get("per_hour_of_positive_overtime_balance") is not None else 4,
            "per_hour_of_unpreferred_period": obj.get("per_hour_of_unpreferred_period") if obj.get("per_hour_of_unpreferred_period") is not None else 2
        })
        return _obj


