# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self

class WorkerRevenue(BaseModel):
    """
    WorkerRevenue
    """ # noqa: E501
    per_hour_of_negative_flextime_balance: Optional[StrictInt] = Field(default=10, description="How much revenue is earned at the end of the period for each flex time balance negative hour")
    per_hour_of_pto: Optional[StrictInt] = Field(default=1000, description="How much revenue is earned for each pto time hour")
    per_hour_of_preferred_period: Optional[StrictInt] = Field(default=5, description="How much revenue is earned for each hour assigned during a preferred period")
    per_hour_of_skilled_work: Optional[Dict[str, StrictInt]] = Field(default=None, description="Extra revenue per skill in euros per hour.         These skills are also used to determine the compatibility with shifts (shift.required_skills) and demands (demand.required_skills).")
    per_hour_of_tagged_work: Optional[Dict[str, StrictInt]] = Field(default=None, description="Extra revenue per tagged work in euros per hour.         This revenue is used to make the assignment fairer towards workers that are lagging behind in the number of shifts with a specific tag.")
    __properties: ClassVar[List[str]] = ["per_hour_of_negative_flextime_balance", "per_hour_of_pto", "per_hour_of_preferred_period", "per_hour_of_skilled_work", "per_hour_of_tagged_work"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkerRevenue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkerRevenue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "per_hour_of_negative_flextime_balance": obj.get("per_hour_of_negative_flextime_balance") if obj.get("per_hour_of_negative_flextime_balance") is not None else 10,
            "per_hour_of_pto": obj.get("per_hour_of_pto") if obj.get("per_hour_of_pto") is not None else 1000,
            "per_hour_of_preferred_period": obj.get("per_hour_of_preferred_period") if obj.get("per_hour_of_preferred_period") is not None else 5,
            "per_hour_of_skilled_work": obj.get("per_hour_of_skilled_work"),
            "per_hour_of_tagged_work": obj.get("per_hour_of_tagged_work")
        })
        return _obj


