# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.day_costs import DayCosts

class TestDayCosts(unittest.TestCase):
    """DayCosts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DayCosts:
        """Test DayCosts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DayCosts`
        """
        model = DayCosts()
        if include_optional:
            return DayCosts(
                per_expected_hour = 56,
                per_flextime_positive_hour = 56,
                per_overtime_hour = 56,
                per_assigned_hour = 56,
                per_idle_hour_between_shifts = 56,
                per_undertime_hour = 56
            )
        else:
            return DayCosts(
        )
        """

    def testDayCosts(self):
        """Test DayCosts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
