# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.schedule_job_config import ScheduleJobConfig

class TestScheduleJobConfig(unittest.TestCase):
    """ScheduleJobConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleJobConfig:
        """Test ScheduleJobConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleJobConfig`
        """
        model = ScheduleJobConfig()
        if include_optional:
            return ScheduleJobConfig(
                adjust_thresholds_on_violation = True,
                webhook_url = '0',
                webhook_secret = '01234567'
            )
        else:
            return ScheduleJobConfig(
        )
        """

    def testScheduleJobConfig(self):
        """Test ScheduleJobConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
