# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.day_time_constraints import DayTimeConstraints

class TestDayTimeConstraints(unittest.TestCase):
    """DayTimeConstraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DayTimeConstraints:
        """Test DayTimeConstraints
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DayTimeConstraints`
        """
        model = DayTimeConstraints()
        if include_optional:
            return DayTimeConstraints(
                max_scheduled_time_minutes = 0.0,
                contractual_minutes = 0.0,
                min_expected_time_minutes = 0.0,
                max_expected_time_minutes = 0.0,
                max_overtime_minutes = 0.0,
                min_assigned_time_minutes = 0.0,
                max_assigned_time_minutes = 0.0,
                max_recovered_time_minutes = 0.0,
                max_pto_time_minutes = 0.0
            )
        else:
            return DayTimeConstraints(
                max_scheduled_time_minutes = 0.0,
        )
        """

    def testDayTimeConstraints(self):
        """Test DayTimeConstraints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
