# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.shift_creation_settings import ShiftCreationSettings

class TestShiftCreationSettings(unittest.TestCase):
    """ShiftCreationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShiftCreationSettings:
        """Test ShiftCreationSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShiftCreationSettings`
        """
        model = ShiftCreationSettings()
        if include_optional:
            return ShiftCreationSettings(
                timezone = '',
                required_skills = [
                    ''
                    ],
                tags = [
                    ''
                    ],
                day_boundary_offset_minutes = 56,
                break_minutes = 30,
                work_duration = pristime_sdk.models.work_duration.WorkDuration(
                    min_minutes = 56, 
                    max_minutes = 56, ),
                continuous_work_duration_before_break = pristime_sdk.models.continuous_work_duration_before_break.ContinuousWorkDurationBeforeBreak(
                    min_minutes = 56, 
                    max_minutes = 56, )
            )
        else:
            return ShiftCreationSettings(
                timezone = '',
                break_minutes = 30,
                work_duration = pristime_sdk.models.work_duration.WorkDuration(
                    min_minutes = 56, 
                    max_minutes = 56, ),
                continuous_work_duration_before_break = pristime_sdk.models.continuous_work_duration_before_break.ContinuousWorkDurationBeforeBreak(
                    min_minutes = 56, 
                    max_minutes = 56, ),
        )
        """

    def testShiftCreationSettings(self):
        """Test ShiftCreationSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
