# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.provided_shifts_durations import ProvidedShiftsDurations

class TestProvidedShiftsDurations(unittest.TestCase):
    """ProvidedShiftsDurations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProvidedShiftsDurations:
        """Test ProvidedShiftsDurations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvidedShiftsDurations`
        """
        model = ProvidedShiftsDurations()
        if include_optional:
            return ProvidedShiftsDurations(
                kept_assignment_minutes = 56,
                changed_assignment_minutes = 56,
                lost_assignment_minutes = 56,
                remained_unassigned_minutes = 56,
                gained_assignment_minutes = 56
            )
        else:
            return ProvidedShiftsDurations(
                kept_assignment_minutes = 56,
                changed_assignment_minutes = 56,
                lost_assignment_minutes = 56,
                remained_unassigned_minutes = 56,
                gained_assignment_minutes = 56,
        )
        """

    def testProvidedShiftsDurations(self):
        """Test ProvidedShiftsDurations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
