# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Authorization` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.worker_revenue import WorkerRevenue

class TestWorkerRevenue(unittest.TestCase):
    """WorkerRevenue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkerRevenue:
        """Test WorkerRevenue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkerRevenue`
        """
        model = WorkerRevenue()
        if include_optional:
            return WorkerRevenue(
                per_hour_of_negative_flextime_balance = 56,
                per_hour_of_pto = 56,
                per_hour_of_preferred_period = 56,
                per_hour_of_skilled_work = {
                    'key' : 56
                    },
                per_hour_of_tagged_work = {
                    'key' : 56
                    }
            )
        else:
            return WorkerRevenue(
        )
        """

    def testWorkerRevenue(self):
        """Test WorkerRevenue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
