# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.durations import Durations

class TestDurations(unittest.TestCase):
    """Durations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Durations:
        """Test Durations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Durations`
        """
        model = Durations()
        if include_optional:
            return Durations(
                provided = pristime_sdk.models.provided_shifts_durations.ProvidedShiftsDurations(
                    kept_assignment_minutes = 56, 
                    changed_assignment_minutes = 56, 
                    lost_assignment_minutes = 56, 
                    remained_unassigned_minutes = 56, 
                    gained_assignment_minutes = 56, ),
                created = 56
            )
        else:
            return Durations(
                provided = pristime_sdk.models.provided_shifts_durations.ProvidedShiftsDurations(
                    kept_assignment_minutes = 56, 
                    changed_assignment_minutes = 56, 
                    lost_assignment_minutes = 56, 
                    remained_unassigned_minutes = 56, 
                    gained_assignment_minutes = 56, ),
                created = 56,
        )
        """

    def testDurations(self):
        """Test Durations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
