# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.api.workforce_scheduling_api import WorkforceSchedulingApi


class TestWorkforceSchedulingApi(unittest.TestCase):
    """WorkforceSchedulingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkforceSchedulingApi()

    def tearDown(self) -> None:
        pass

    def test_create_schedule_job(self) -> None:
        """Test case for create_schedule_job

        Create Workforce Schedule Optimization Job
        """
        pass

    def test_get_schedule_job(self) -> None:
        """Test case for get_schedule_job

        Get Scheduling Job Status and Results
        """
        pass


if __name__ == '__main__':
    unittest.main()
