# coding: utf-8

"""
    Pristime Workforce Scheduling API

             ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com         

    The version of the OpenAPI document: 2.0.0
    Contact: antoine.hachez@pristime.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pristime_sdk.models.period_metrics import PeriodMetrics

class TestPeriodMetrics(unittest.TestCase):
    """PeriodMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeriodMetrics:
        """Test PeriodMetrics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeriodMetrics`
        """
        model = PeriodMetrics()
        if include_optional:
            return PeriodMetrics(
                expected_time_minutes = 0.0,
                overtime_minutes = 0.0,
                assigned_time_minutes = 0.0,
                recovered_time_minutes = 0.0,
                pto_time_minutes = 0.0,
                flextime_negative_minutes = 0.0,
                flextime_positive_minutes = 0.0,
                flextime_balance_minutes = 56,
                active_days = 0.0,
                expected_days = 0.0
            )
        else:
            return PeriodMetrics(
        )
        """

    def testPeriodMetrics(self):
        """Test PeriodMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
